### ISSUE TITLE
[BUG] | Cenarion Circle can become monarchy

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#584]
**Mod Version**
45c51858

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Cenarion Circle can create custom Empire to become Monarchy
Cenarion Circle succession will be changed to Gavelkind
When your characters dies, it will be game over

**Steps to reproduce the issue:**
Create custom Empire as Cenarion Circle

**Upload an attachment below: .zip of your save, or screenshots:**

<details>

![image](https://user-images.githubusercontent.com/46576860/62324129-824ff500-b4b1-11e9-8594-5abd23453567.png)

</details>

**Comment by sejtalk** [comment]
fixed

**Comment by zumbak04** [comment]
> fixed [8d576df](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/commit/8d576df91f48c34307635949c66d8b11aab31bd9)

@sejtalk still not fixed. You can reform Empire of Zul and become Monarchy.
<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46384992/71373100-7b945c80-25cf-11ea-8dd2-922e547a4143.png)
![image](https://user-images.githubusercontent.com/46384992/71373105-8222d400-25cf-11ea-856e-d25eb5d1bb65.png)

</details>
