### ISSUE TITLE
Ruled too long

### ISSUE THREAD

**Issue by MemeWizard** [Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth#809]
**Mod Version**
efdb140b

**What expansions do you have installed?**
All

**Please explain your issue in as much detail as possible:**
Immortal character don't like Immortal rulers because they ruled too long

**Steps to reproduce the issue:**
Rule too long

**Upload an attachment below: .zip of your save, or screenshots:**

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/65995550-70350780-e49e-11e9-8dcb-e0dbb8565c54.png)

</details>

**Comment by zumbak04** [comment]
Fixed!

**Comment by MemeWizard** [comment]
Not fixed

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/73736425-cb7b4d00-4751-11ea-81c9-dbcab5f02894.png)

</details>

[Ahn'qiraj585_03_10.zip](https://github.com/Warcraft-GoA-Development-Team/Warcraft-Guardians-of-Azeroth/files/4152690/Ahn.qiraj585_03_10.zip)

**Comment by MemeWizard** [comment]
Short reign works strange too

<details>
<summary>Click to expand</summary>

![image](https://user-images.githubusercontent.com/46576860/74029295-6d52a200-49bd-11ea-91ad-85f5995008de.png)
![image](https://user-images.githubusercontent.com/46576860/74029313-780d3700-49bd-11ea-8e6a-7aea49779735.png)

</details>

**Comment by zumbak04** [comment]
Fixing it, I started to think... what is a problem of Ruled too long? Isn't it a good way to make immortal realms more dynamic? I would return it.

**Comment by MemeWizard** [comment]
Idk, imo, it will be weird if immortal vassals will not like immortal liege, since their life spawn is more or less the same.
It can make sense if mortal vassal don't like immortal liege because their rule is too long, tho.

**Comment by zumbak04** [comment]
> Idk, imo, it will be weird if immortal vassals will not like immortal liege, since their life spawn is more or less the same.

The same and that's a problem. Immortal vassals should prefer weak and mortal liege because the chances of installing their dynasties are higher. So basically, everyone should dislike immortals and like mortals.

**Comment by arithon** [comment]
well, content vassals might like immortal lieges, especially if liege likes them
